### ISSUE TITLE
_public n'est pas lu

### ISSUE THREAD

**Issue by lipki** [franck-paul/mymeta#1]
Je m'arrache les cheveux sur une mise à jour vers Dotclear 2.19 qui ne passe pas tout seul.
Bref, j'y suis presque sauf pour ce plugin qui ne fonctionne plus.

Le problème se pose en 0.5.3 et 0.5.4.
L'administration du plugin fonctionne, mais pas les balises tpl.
Après une exploration en profondeur, le fichier _public.php n'est pas lu.

Et je ne comprends pas et je ne vois pas ce que je peux faire surtout.

Voilà, si quelqu'un a une idée ?
merci d'avance.

**Comment by lipki** [comment]
Et sinon en rapport, mais pas vraiment, dotaddict.org et mort ?

**Comment by franck-paul** [comment]
Oui je sais pour les balises, je n'ai pas encore pris le temps de regarder pourquoi (mais il faut dire que c'est une usine à gaz la dedans)

Sinon oui DA est HS pour le moment

**Comment by lipki** [comment]
Ok Maj
Mon problème était causé par un autre plugin charger juste avant MyMeta, et qui interrompe le chargement silencieusement.
ici : https://github.com/dotclear/dotclear/blob/c141dcb9cfa8440a6f94a1d0cbded853714f5cb1/inc/core/class.dc.modules.php#L780
